name: "Formulario de Pase a Certificación"
description: "Este formulario es para documentar los aspectos relacionados con el proceso de pase a certificación."
body:
  - type: markdown
    attributes:
      value: |
        Por favor, completa la siguiente información para facilitar el proceso de pase a certificación.

  - type: dropdown
    id: cbo_squad_solicitante
    attributes:
      label: "Squad Solicitante"
      options:
        - SQUAD 1
        - SQUAD 2
        - SQUAD 3
        - SQUAD 4
    validations:
      required: true

  - type: input
    id: in_product_owner
    attributes:
      label: "Product Owner"
      description: "Indica el Product Owner responsable del producto."
      placeholder: "Ej. Juan Pérez"
    validations:
      required: true

  - type: input
    id: in_chapter_lead
    attributes:
      label: "Chapter Lead"
      description: "Indica el Chapter Lead responsable del producto."
      placeholder: "Ej. Gustavo López"
    validations:
      required: true

  - type: input
    id: in_data_engineer_responsable
    attributes:
      label: "Data Engineer Responsable"
      description: "Indica el Data Engineer Responsable responsable del producto."
      placeholder: "Ej. Joaquin Abanto"
    validations:
      required: true

  - type: input
    id: in_analista_seguridad
    attributes:
      label: "Analista de Seguridad"
      description: "Indica el Analista de Seguridad responsable del producto."
      placeholder: "Ej. Ana Martínez"
    validations:
      required: true

  - type: input
    id: in_custodio_tecnico
    attributes:
      label: "Custodio Técnico"
      description: "Indica el Custodio Técnico responsable del producto."
      placeholder: "Ej. Luis González"
    validations:
      required: true

  - type: input
    id: in_data_steward
    attributes:
      label: "Data Steward"
      description: "Indica el Data Steward responsable del producto."
      placeholder: "Ej. Jose Ramírez"
    validations:
      required: true

  - type: input
    id: in_link_jira
    attributes:
      label: "Link a Jira"
      description: "Indica el link a la tarea en Jira."
      placeholder: "Ej. https://jira.example.com/browse/PROJ-123"
    validations:
      required: true