name: "Formulario de Prueba"
description: "Prueba"
body:
  - type: markdown
    attributes:
      value: |
        Markdown de prueba

  - type: input
    id: version_software
    attributes:
      label: "Versión del software"
      description: "Indica la versión donde encontraste el problema."
      placeholder: "Ej. v2.4.1"
    validations:
      required: true

  - type: textarea
    id: codigo_error
    attributes:
      label: "Logs o Código de error"
      description: "Pega aquí el mensaje de error completo."
      placeholder: "Pega el bloque de código aquí..."
      render: bash # Formatea automáticamente el texto como código Bash/Terminal
    validations:
      required: false

  - type: dropdown
    id: sistema_operativo
    attributes:
      label: "Sistema Operativo"
      options:
        - Windows
        - macOS
        - Linux
        - Otro
    validations:
      required: true

  - type: checkboxes
    id: terminos_comunidad
    attributes:
      label: "Acuerdos"
      options:
        - label: "He leído el código de conducta."
          required: true
        - label: "Estoy dispuesto a ayudar a solucionar este issue."
          required: false

  - type: reactions
    id: tipo_feedback
    attributes:
      label: "¿Cómo calificarías este problema?"
